include_HEADERS = \
				  		 src/swm-include.h \
						 src/lammps/lammps.h \
						 src/lammps/lammps_model.h \
						 src/nekbone/nekbone_swm_user_code.h \
						 src/nekbone/triplet.h	\
						 src/nekbone/cubiclattice.h \
						 src/nearest_neighbor/nearest_neighbor_swm_user_code.h \
						 src/nearest_neighbor/boost_ptree_array_to_std_vector.h \
						 src/incast/all_to_one_swm_user_code.h \
						 src/spread/one_to_many_swm_user_code.h \
						 src/many_to_many/many_to_many_swm_user_code.h \
						 src/allreduce/allreduce.h \
						 src/milc/milc_swm_user_code.h

src_libswm_la_SOURCES = src/lammps/lammps.cpp	\
						src/nekbone/cubiclattice.cpp	\
						src/nekbone/nekbone_swm_user_code.cpp	\
						src/nearest_neighbor/nearest_neighbor_swm_user_code.cpp \
						src/incast/all_to_one_swm_user_code.cpp \
						src/spread/one_to_many_swm_user_code.cpp \
						src/many_to_many/many_to_many_swm_user_code.cpp \
						src/allreduce/allreduce.cpp \
						src/milc/milc_swm_user_code.cpp

dist_data_DATA = src/lammps/lammps_workload.json \
			  src/lammps/lammps_workload1.json \
			  src/nearest_neighbor/skeleton.json \
			  src/nekbone/workload.json \
			  src/nekbone/workload1.json \
			  src/point_to_point/example.json \
			  src/incast/incast.json \
			  src/incast/incast1.json \
			  src/incast/incast2.json \
			  src/spread/spread_workload.json \
			  src/many_to_many/many_to_many_workload.json \
			  src/many_to_many/many_to_many_workload1.json \
			  src/allreduce/allreduce_workload.json \
			  src/allreduce/allreduce32_workload.json \
			  src/allreduce/allreduce256_workload.json \
			  src/milc/milc_skeleton.json


				
